version: 1
build:
  main: x/../
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 200000000untrn
  - 200000000stake
faucet:
  name: bob
  coins:
  - 500000ustrd
  - 100000stake
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
